name: Node.js Package

on:
  push:
    branches:
      - issue-942

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: dmitry-shibanov/setup-node@v-dmshib/fix-arm64-for-windows
        with:
          node-version: 20
          cache: 'yarn'
          registry-url: https://npm.pkg.github.com
          scope: '@priyagupta108'
      - name: Prepare NPM credentials
        run: |
           echo npmAuthToken: "$NODE_AUTH_TOKEN" >> ./.yarnrc.yml
        env:
           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
      - run: yarn workspaces focus --all --production
      - run: yarn npm publish 
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
       