name: Check .npmrc on Windows

on:
  push:
    branches:
      - issue-995

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      env:
        NODE_AUTH_TOKEN: "MyAuthToken"
      with:
        registry-url: 'https://my-repo.example.com/npm-private/'
        scope: 'myscope'
      
    - name: Check .npmrc in specified path
      run: dir $Env:NPM_CONFIG_USERCONFIG
      shell: pwsh

    - name: Display .npmrc if exists
      if: success()
      run: cat $Env:NPM_CONFIG_USERCONFIG
      shell: pwsh
