name: Node.js CI

on:
  push:
    branches: [ yarn-test ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dmitry-shibanov/setup-node@v-dmshib/fix-arm64-for-windows
      with:
        node-version: '20'
        cache: 'yarn'
    - run: yarn install
    - run: yarn test
    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
