name: Node.js Package

on:
  push:
    branches:
      - pnpm-test
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Setup Node.js
      uses: priyagupta108/setup-node@PR-927
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Test
      run: pnpm test

    - name: Publish
      run: echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > .npmrc && pnpm publish --no-git-checks
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GIT_TOKEN }}
