name: Node.js Package

on:
  push:
    branches:
      - pnpm-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Setup Node.js
      uses: dmitry-shibanov/setup-node@v-dmshib/fix-arm64-for-windows
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Test
      run: pnpm test

    - name: Publish
      run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > .npmrc && pnpm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GIT_TOKEN }}