name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dmitry-shibanov/setup-node@v-dmshib/fix-arm64-for-windows
       with:
        node-version: '16.x'
        cache: 'npm'
    - run: npm ci
    - run: npm run test
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
