name: Issue 995 Workflow

on:
  push:
    branches:
      - issue-995

jobs:
  check-npmrc-path:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Echo RUNNER_TEMP
        run: echo ${RUNNER_TEMP}

      - name: List files in RUNNER_TEMP
        run: ls -al ${RUNNER_TEMP}
