name: Node.js Package

on:
  push:
    branches:
      - yarn-test


jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v5
        with:
          node-version: '20.16.0'
          cache: 'npm'
          
      
       
      - run: npm ci
     
