name: Node.js Package

on:
  push:
    branches:
      - yarn-test


jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: priyagupta108/setup-node@PR-927
        with:
          node-version: 20
          cache: 'yarn'
          registry-url: https://npm.pkg.github.com
          scope: '@priyagupta108'
      - name: Prepare NPM credentials
        run: |
           echo npmAuthToken: "$NODE_AUTH_TOKEN" >> ./.yarnrc.yml
        env:
           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
      - run: yarn install
      - run: yarn npm publish 
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
       
